version: '3'

services:
        zookeeper:
                image: confluentinc/cp-zookeeper:7.0.3
                hostname: zookeeper
                container_name: zookeeper
                ports:
                        - "2181:2181"
                environment:
                        ZOOKEEPER_CLIENT_PORT: 2181
                        ZOOKEEPER_SERVER_ID: 1
                        ZOOKEEPER_SERVERS: zookeeper:2088:3888
                volumes:
                        - ./data:/data
                        - ./datalog:/datalog
        kafka1:
                image: confluentinc/cp-kafka:7.0.3
                hostname: kafka1
                ports:
                        - "9091:9091"
                environment:
                        KAFKA_ADVERTISED_LISTENERS: LISTENER_DOCKER_INTERNAL://kafka1:19091,LISTENER_DOCKER_EXTERNAL://${DOCKER_HOST_IP:-127.0.0.1}:9091
                        KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: LISTENER_DOCKER_INTERNAL:PLAINTEXT,LISTENER_DOCKER_EXTERNAL:PLAINTEXT
                        KAFKA_INTER_BROKER_LISTENER_NAME: LISTENER_DOCKER_INTERNAL
                        KAFKA_ZOOKEEPER_CONNECT: "zookeeper:2181"
                        KAFKA_BROKER_ID: 1
                        KAFKA_LOG4J_LOGGERS: "kafka.controller=INFO,kafka.producer.async.DefaultEventHandler=INFO,state.change.logger=INFO"
                        KAFKA_JMX_PORT: 49991
                volumes:
                        - ./kafka/kafka1/data:/var/lib/kafka/data
                depends_on:
                        - zookeeper
        manager:
                image: ghcr.io/eshepelyuk/dckr/cmak-3.0.0.6:latest
                restart: always
                ports:
                        - 9000:9000
                environment:
                        - ZK_HOSTS=zookeeper:2181
                depends_on:
                        - zookeeper